# Generated by Django 5.0.8 on 2024-08-07 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sort_order', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Encoding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding_id', models.SlugField(max_length=250, unique=True)),
                ('encoding_type', models.CharField(choices=[('fixed', 'Fixed'), ('variable', 'Variable'), ('other', 'Other')], default='other', max_length=32)),
                ('encoding', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('levelNumber', models.AutoField(primary_key=True, serialize=False, verbose_name='Level Number')),
                ('levelVersion', models.PositiveIntegerField(default=1, verbose_name='Level Version')),
                ('sort_order', models.PositiveIntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='levels', to='puzzles.category')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='LevelNameLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=80)),
                ('sort_order', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('level_name_of', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='levelName', to='puzzles.level')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(blank=True, max_length=250, null=True)),
                ('menuVersion', models.PositiveIntegerField(default=1)),
                ('encodings', models.ManyToManyField(to='puzzles.encoding')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='puzzles.menu'),
        ),
        migrations.CreateModel(
            name='MenuFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='puzzles.menu')),
            ],
        ),
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puzzle_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=250)),
                ('line_length', models.PositiveIntegerField(default=13)),
                ('init', models.CharField(blank=True, default='', max_length=50)),
                ('winText', models.CharField(blank=True, default='', max_length=50)),
                ('type', models.CharField(choices=[('Decode', 'Decode'), ('Encode', 'Encode')], default='Decode', max_length=32)),
                ('encoding_name', models.CharField(choices=[('SingleBit', 'Single Bit'), ('DoubleBit', 'Double Bit'), ('AlphaLengthA1', 'Alpha-Length A1'), ('ThreeBitOctal', 'Three-Bit Octal'), ('4bHex', 'Four-Bit Hex'), ('5bA1', 'Five-Bit A1'), ('other', 'Other')], default='AlphaLengthA1', max_length=32)),
                ('encoding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puzzles', to='puzzles.encoding')),
                ('level', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='puzzles', to='puzzles.level')),
            ],
            options={
                'ordering': ['puzzle_number'],
            },
        ),
        migrations.CreateModel(
            name='DailyPuzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('puzzle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puzzle_on_date', to='puzzles.puzzle')),
            ],
        ),
        migrations.CreateModel(
            name='ClueLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=80)),
                ('sort_order', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('clue_in', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clue', to='puzzles.puzzle')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WinMessageLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=80)),
                ('sort_order', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('win_message_in', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winMessage', to='puzzles.puzzle')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
