# Generated by Django 5.0.8 on 2024-09-25 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puzzle',
            name='encoding_name',
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='line_length',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
