# Generated by Django 3.0.6 on 2020-05-16 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0002_puzzle'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='clue_lines',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='puzzles.Line'),
        ),
    ]
