# Generated by Django 5.0.8 on 2025-04-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0002_remove_puzzle_encoding_name_alter_puzzle_line_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='level',
            options={'ordering': ['category', 'sort_order']},
        ),
        migrations.AlterModelOptions(
            name='puzzle',
            options={'ordering': ['level__category', 'level', 'puzzle_number']},
        ),
        migrations.AddField(
            model_name='level',
            name='slug',
            field=models.SlugField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='slug',
            field=models.SlugField(blank=True, max_length=250),
        ),
    ]
