# Generated by Django 5.0.8 on 2025-04-15 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0003_alter_level_options_alter_puzzle_options_level_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
    ]
