# Generated by Django 3.0.6 on 2020-05-16 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0003_puzzle_clue_lines'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puzzle',
            name='clue_lines',
        ),
        migrations.AddField(
            model_name='line',
            name='clue_in',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='clue_lines', to='puzzles.Puzzle'),
        ),
    ]
