# Generated by Django 3.0.6 on 2020-05-16 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0004_auto_20200516_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='clue_in',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clue_lines', to='puzzles.Puzzle'),
        ),
    ]
