# Generated by Django 5.0.8 on 2025-07-19 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0004_alter_level_slug_alter_puzzle_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='menuVersion',
        ),
        migrations.AddField(
            model_name='dailypuzzle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='line_length',
            field=models.PositiveIntegerField(default=24),
        ),
    ]
