# Generated by Django 5.0.8 on 2026-07-23 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0005_remove_menu_menuversion_dailypuzzle_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='clock',
            field=models.CharField(blank=True, choices=[('none', 'Taste — player-paced, no clock'), ('advance', 'Treat — focus auto-advances, timed'), ('scroll', 'Dessert — conveyor carries letters past a judgment line')], help_text='Chocolate only. Blank uses the game default (Dessert).', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='maxStrikes',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Dessert only. Missed letters before the run ends. Blank uses the game default (10).', null=True, verbose_name='Max strikes'),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='scrollAccel',
            field=models.FloatField(blank=True, help_text='Dessert only. Rows per second added every 10 judged letters. Blank uses the game default (0.04).', null=True, verbose_name='Scroll acceleration'),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='scrollSpeed',
            field=models.FloatField(blank=True, help_text='Dessert only. Belt speed in rows per second. Blank uses the game default (0.20).', null=True, verbose_name='Scroll speed'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='type',
            field=models.CharField(choices=[('Decode', 'Decode'), ('Encode', 'Encode'), ('Chocolate', 'Chocolate')], default='Decode', max_length=32),
        ),
    ]
