# Generated by Django 3.0.6 on 2020-06-06 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0005_auto_20200516_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='win_message_in',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='win_message_lines', to='puzzles.Puzzle'),
        ),
    ]
