# Generated by Django 5.0.8 on 2026-07-28 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0006_puzzle_clock_puzzle_maxstrikes_puzzle_scrollaccel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puzzle',
            name='name',
        ),
    ]
