# Generated by Django 3.0.6 on 2020-06-14 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0006_line_win_message_in'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClueLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=80)),
                ('length', models.IntegerField()),
                ('clue_in', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clue_lines', to='puzzles.Puzzle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WinMessageLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=80)),
                ('length', models.IntegerField()),
                ('win_message_in', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='win_message_lines', to='puzzles.Puzzle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Line',
        ),
    ]
