# Generated by Django 3.0.6 on 2020-06-14 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0007_auto_20200614_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='line_length',
            field=models.PositiveIntegerField(default=13),
        ),
    ]
