# Generated by Django 5.0.8 on 2026-07-29 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0007_remove_puzzle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
    ]
