# Generated by Django 5.0.8 on 2026-08-12 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0008_alter_puzzle_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='winText',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
