# Generated by Django 3.0.6 on 2020-06-14 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0008_puzzle_line_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='init_text',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='win_text',
            field=models.CharField(default='', max_length=50),
        ),
    ]
