# Generated by Django 5.0.8 on 2026-08-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0009_alter_puzzle_wintext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='line_length',
            field=models.PositiveIntegerField(default=18),
        ),
    ]
