# Generated by Django 3.0.6 on 2020-06-14 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0009_auto_20200614_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='encoding',
            field=models.CharField(choices=[('SingleBit', 'Single Bit'), ('DoubleBit', 'Double Bit'), ('AlphaLengthA1', 'Alpha-Length A1'), ('ThreeBitOctal', 'Three-Bit Octal'), ('FourBitHex', 'Four-Bit Hex'), ('5bA1', 'Five-Bit A1')], default='AlphaLengthA1', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='puzzle',
            name='type',
            field=models.CharField(choices=[('Decode', 'Decode'), ('Encode', 'Encode')], default='Decode', max_length=32),
            preserve_default=False,
        ),
    ]
