# Generated by Django 3.0.6 on 2020-06-19 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0011_auto_20200614_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clueline',
            name='clue_in',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clue', to='puzzles.Puzzle'),
        ),
        migrations.AlterField(
            model_name='winmessageline',
            name='win_message_in',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winMessage', to='puzzles.Puzzle'),
        ),
    ]
