# Generated by Django 3.0.6 on 2020-06-20 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0012_auto_20200619_2306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puzzle',
            old_name='init_text',
            new_name='init',
        ),
        migrations.RenameField(
            model_name='puzzle',
            old_name='win_text',
            new_name='winText',
        ),
    ]
