# Generated by Django 3.0.6 on 2020-06-20 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0013_auto_20200620_0007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('levelNumber', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='LevelNameLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=80)),
                ('length', models.IntegerField()),
                ('level_name_of', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='levelName', to='puzzles.Level')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='puzzle',
            name='level',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='puzzles', to='puzzles.Level'),
        ),
    ]
