# Generated by Django 3.0.6 on 2020-07-26 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0017_auto_20200726_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='levelVersion',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menuVersion',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
