# Generated by Django 3.2.15 on 2022-09-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0021_auto_20220820_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='puzzle_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clueline',
            name='sort_order',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='levelnameline',
            name='sort_order',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='winmessageline',
            name='sort_order',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
