# Generated by Django 3.2.15 on 2022-11-08 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0022_auto_20220902_1749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clueline',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='levelnameline',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='puzzle',
            options={'ordering': ['puzzle_number']},
        ),
        migrations.AlterModelOptions(
            name='winmessageline',
            options={'ordering': ['sort_order']},
        ),
    ]
