# Generated by Django 3.2.15 on 2022-11-12 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0024_auto_20221109_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sort_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
