# Generated by Django 3.2.15 on 2022-11-12 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0025_category_sort_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sort_order'], 'verbose_name_plural': 'Categories'},
        ),
    ]
