# Generated by Django 5.0.4 on 2024-04-29 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0027_menufile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encoding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding_id', models.SlugField(max_length=250, unique=True)),
            ],
        ),
    ]
