# Generated by Django 5.0.4 on 2024-04-29 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0028_encoding'),
    ]

    operations = [
        migrations.AddField(
            model_name='encoding',
            name='menus',
            field=models.ManyToManyField(related_name='encodings', to='puzzles.menu'),
        ),
    ]
