# Generated by Django 5.0.4 on 2024-04-29 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0029_encoding_menus'),
    ]

    operations = [
        migrations.AddField(
            model_name='encoding',
            name='encoding_type',
            field=models.CharField(choices=[('SingleBit', 'Single Bit'), ('DoubleBit', 'Double Bit'), ('AlphaLengthA1', 'Alpha-Length A1'), ('ThreeBitOctal', 'Three-Bit Octal'), ('FourBitHex', 'Four-Bit Hex'), ('5bA1', 'Five-Bit A1'), ('Other', 'Other')], default='Other', max_length=32),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='encoding',
            field=models.CharField(choices=[('SingleBit', 'Single Bit'), ('DoubleBit', 'Double Bit'), ('AlphaLengthA1', 'Alpha-Length A1'), ('ThreeBitOctal', 'Three-Bit Octal'), ('FourBitHex', 'Four-Bit Hex'), ('5bA1', 'Five-Bit A1'), ('Other', 'Other')], default='AlphaLengthA1', max_length=32),
        ),
    ]
