# Generated by Django 5.0.4 on 2024-04-29 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0030_encoding_encoding_type_alter_puzzle_encoding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encoding',
            name='encoding_type',
            field=models.CharField(choices=[('Fixed', 'fixed'), ('Variable', 'variable'), ('Other', 'other')], default='Other', max_length=32),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='encoding',
            field=models.CharField(choices=[('Fixed', 'fixed'), ('Variable', 'variable'), ('Other', 'other')], default='AlphaLengthA1', max_length=32),
        ),
    ]
