# Generated by Django 5.0.4 on 2024-04-29 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0031_alter_encoding_encoding_type_alter_puzzle_encoding'),
    ]

    operations = [
        migrations.AddField(
            model_name='encoding',
            name='encoding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
