# Generated by Django 5.0.4 on 2024-04-29 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0032_encoding_encoding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encoding',
            name='menus',
        ),
        migrations.AddField(
            model_name='menu',
            name='encodings',
            field=models.ManyToManyField(to='puzzles.encoding'),
        ),
    ]
