# Generated by Django 5.0.4 on 2024-04-29 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0033_remove_encoding_menus_menu_encodings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encoding',
            name='encoding_type',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('variable', 'Variable'), ('other', 'Other')], default='other', max_length=32),
        ),
        migrations.AlterField(
            model_name='menu',
            name='encodings',
            field=models.ManyToManyField(related_name='menus', to='puzzles.encoding'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='encoding',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('variable', 'Variable'), ('other', 'Other')], default='AlphaLengthA1', max_length=32),
        ),
    ]
