# Generated by Django 5.0.4 on 2024-04-29 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0034_alter_encoding_encoding_type_alter_menu_encodings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='encodings',
            field=models.ManyToManyField(to='puzzles.encoding'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='encoding',
            field=models.CharField(choices=[('SingleBit', 'Single Bit'), ('DoubleBit', 'Double Bit'), ('AlphaLengthA1', 'Alpha-Length A1'), ('ThreeBitOctal', 'Three-Bit Octal'), ('4bHex', 'Four-Bit Hex'), ('5bA1', 'Five-Bit A1'), ('other', 'Other')], default='AlphaLengthA1', max_length=32),
        ),
    ]
