# Generated by Django 5.0.4 on 2024-04-30 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0035_alter_menu_encodings_alter_puzzle_encoding'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='encoding_name',
            field=models.CharField(choices=[('SingleBit', 'Single Bit'), ('DoubleBit', 'Double Bit'), ('AlphaLengthA1', 'Alpha-Length A1'), ('ThreeBitOctal', 'Three-Bit Octal'), ('4bHex', 'Four-Bit Hex'), ('5bA1', 'Five-Bit A1'), ('other', 'Other')], default='AlphaLengthA1', max_length=32),
        ),
    ]
