# Generated by Django 5.0.4 on 2024-04-30 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0037_copy_encoding_id_to_encoding_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puzzle',
            name='encoding',
        ),
    ]
